# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec646b47d4624570725eabe76087f9ca345c78488f6860a76c4c18e65765f3daae7f4746fd485327749e4f9f6d8534ead254935b9a69cc824d2ad1217fa570c3

test:
  secret_key_base: a2f03d4641976944dbb292c67c0320eae7cccc8af1d23364f1aafc284628f2e8263de6e48f7fc4ee7e8cac81989cb3ad7ad154fe4a827f7e8b26e32ac0e57223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
